### ISSUE TITLE
Scrutinizer Coverage

### ISSUE THREAD

**Issue by MohammadForouhesh** [MohammadForouhesh/crf-pos-persian#8]
```yaml
checks:
    python:
        code_rating: true
        duplicate_code: true
        typecheck_maybe_no_member: true
        classes_valid_slots: true
        basic_missing_reversed_argument: true

build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - py-scrutinizer-run
                    - 
                        command: pylint-run [main.py]
                        use_website_config: true
        coverage:
            tests:
                override:
                    - command: coverage run main.py
                      coverage:
                        file: '.coverage'
                        # nfig_file: '.coveragerc'
                        format: 'py-cc'
        tests: true
filter:
    excluded_paths:
        - '*/test/*'
```
